### ISSUE TITLE
Vanilla seed

### ISSUE THREAD

**Issue by ogur** [dashrando/dash-rando-app#3]
Do you know what seed gives vanilla items placement?
I know a little bit against the whole concept of randomizer, but I'd like to play vanilla(-ish) game with timer, ammo counters and skipped intro.

**Comment by MassHesteria** [comment]
Hmm, don't know about that one. It might be nice if a seed of 0 skipped randomizing the items, but it does not currently work that way. Technically, the items could randomly be put in a close to correct place. Not 100% correct though because the major (eTank) in the room before HJB is now a minor item, and the minor (Super Missile) to the right after Phantoon is now a major. Not sure which seed would get you the closest though. Also, it's worth noting that using the dash app would give you the other game changes associated with dash that are def not vanilla (starter charge beam, suit damage changes, etc.).

I actually really like the idea of having seed 0 keep items in their vanilla locations (even the previously mentioned swap could be put back to normal). I think it would be really interesting to see what kind of times folks could get on a vanilla dash seed. We will definitely consider this for the next release.

**Comment by ogur** [comment]
Yeah, I'm aware about other changes hence "vanillish" :)

Anyway thanks for the response I'll looking forward to future releases.

**Comment by MassHesteria** [comment]
I played with the code today and added support for generating a dash seed with vanilla item locations. The randomization dropdown now offers Major / Minor, Full, and Vanilla. I've attach a build of the app if you'd like to try it.
[dash-app-v9-vanilla.zip](https://github.com/dashrando/dash-rando-app/files/4978468/dash-app-v9-vanilla.zip)

**Comment by ogur** [comment]
I've tested it and that's pretty much what I wanted, so thanks a lot!

(My time was 1:57 but I'm not a speedrunner :P)

**Comment by dashrando** [comment]
GG 👍
